#ifndef DEFINE_H
#define DEFINE_H

#define TOP_SCREEN_WIDTH  400
#define BOTTOM_SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define TOP_SCREEN_SIZE TOP_SCREEN_WIDTH * SCREEN_HEIGHT * 2
#define BOTTOM_SCREEN_SIZE BOTTOM_SCREEN_WIDTH * SCREEN_HEIGHT * 2

#endif